# vim: set expandtab shiftwidth=2 tabstop=8 textwidth=0:

.templates_sha: &template_sha 18194044f0f984c8815bc9a1a146582f6bf15d41 # see https://docs.gitlab.com/ee/ci/yaml/#includefile

include:
  # Fedora container builder template
  - project: 'freedesktop/ci-templates'
    ref: *template_sha
    file: '/templates/fedora.yml'

variables:
  FDO_DISTRIBUTION_PACKAGES: 'python3-flake8 python3-parse python3-pyudev python3-pypandoc pandoc'
  FDO_DISTRIBUTION_VERSION: 33
  FDO_UPSTREAM_REPO: 'libevdev/hid-tools'
  FDO_DISTRIBUTION_TAG: '2020-01-14.1'

stages:
  - prep
  - build

container-prep:
  extends:
    - .fdo.container-build@fedora
  stage: prep
  variables:
    GIT_STRATEGY: none

.default_image:
  extends:
    - .fdo.distribution-image@fedora
  needs:
    - container-prep

flake:
  extends: .default_image
  stage: build
  script:
    # The proper way is to run:
    # python3 setup.py flake8
    # but we want to also check the `tests` folder, so call flake8 directly
    - flake8

install:
  extends: .default_image
  stage: build
  script:
    - python3 setup.py install

install_no_man_pages:
  extends: .default_image
  stage: build
  script:
    - dnf remove -y pandoc python3-pypandoc
    - python3 setup.py install
